apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone3 
  namespace: cep-project1 
  labels:
    app: pgdevops-capstone3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgdevops-capstone3 
  template:
    metadata:
      labels:
        app: pgdevops-capstone3
    spec:
      containers:
        - name: capstone-project3
          image: purusothaman/capstone-project3:pgdevopsv1
          ports:
            - containerPort: 8080
