pipeline {
    agent { node { label 'Master-Node' } }
     
  
    stages{
        
        stage('List pods') {
            steps{
                withKubeConfig([credentialsId: '50c1b910-06de-4418-92e6-d636bb510722',
 
                    serverUrl: 'https://192.168.222.7:6443',
                    namespace: 'default'
                    ]) {
                sh 'kubectl get nodes -o wide'
                sh 'kubectl apply -f gs-spring-boot-docker/deploy_k8s.yaml
                }
            }
        }
    }
}
