apiVersion: v1
kind: Service
metadata:
  name: capstone3-service
  namespace: cep-project1 
spec:
  type: NodePort
  selector:
          app: pgdevops-capstone3 
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004
